name: Laravel Testing

on:
  pull_request:

jobs:
  laravel-testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docker

    steps:
      - uses: actions/checkout@v3
        with:
          path: laravel

      - uses: actions/checkout@v3
        with:
          repository: nocch12/realworld-laravel.docker
          path: docker

      - name: Ubuntu Version
        run: cat /etc/os-release

      - name: Docker Version
        run: docker version

      - name: Docker Compose Build and Up
        run: |
          docker-compose build
          docker-compose up -d

      - name: Docker Compose Process
        run: docker-compose ps -a

      - name: PHP, Composer Version
        run: |
          docker-compose exec -T app php --version
          docker-compose exec -T app composer --version

      - name: Composer Install
        if: steps.cache.outputs.cache-hit != 'true'
        run: docker-compose exec -T app composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Composer Dump Autoload
        run: docker-compose exec -T app composer dump-autoload -q

      - name: Laravel Settings
        run: |
          docker-compose exec -T app cp .env.example .env
          docker-compose exec -T app php artisan key:generate
          docker-compose exec -T app php artisan optimize
          docker-compose exec -T app chmod -R 777 storage bootstrap/cache

      - name: Laravel Version
        run: docker-compose exec -T app php artisan --version

      - name: Laravel Migrate Testing
        run: docker-compose exec -T app php artisan migrate

      - name: Laravel Rollback Testing
        run: docker-compose exec -T app php artisan migrate:refresh

      - name: Laravel Seeding Testing
        run: docker-compose exec -T app php artisan db:seed

      - name: Laravel PHPUnit Testing
        run: |
          docker-compose exec -T app php artisan config:clear
          docker-compose exec -T app php artisan test
